export * from './side-menu/side-menu.component';
export * from './page-dashboard/page-dashboard.component';
export * from './page-posts/page-posts.component';
export * from './page-albums/page-albums.component';
export * from './page-photos/page-photos.component';
export * from './page-not-found/page-not-found.component';
export * from './breadcrumbs/breadcrumbs.component';
export * from './layout-page/layout-page.component';
export * from './loader/loader.component';
